//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dashboard.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dashboard.Tests.TestResources", typeof(TestResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;actions&quot; : [
        ///    {
        ///      &quot;parameters&quot; : [
        ///        {
        ///          &quot;name&quot; : &quot;GitBranchOrCommit&quot;,
        ///          &quot;value&quot; : &quot;${ghprbTargetBranch}&quot;
        ///        },
        ///        {
        ///          &quot;name&quot; : &quot;GitRepoUrl&quot;,
        ///          &quot;value&quot; : &quot;https://github.com/dotnet/roslyn-internal.git&quot;
        ///        },
        ///        {
        ///          &quot;name&quot; : &quot;GitRefSpec&quot;,
        ///          &quot;value&quot; : &quot;&quot;
        ///        },
        ///        {
        ///          &quot;name&quot; : &quot;sha1&quot;,
        ///          &quot;value&quot; : &quot;origin/pr/11091/merge&quot;
        ///        },
        ///        {
        ///          &quot;name&quot; : &quot;ghprbActualCommit&quot;, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BuildFailure1 {
            get {
                return ResourceManager.GetString("BuildFailure1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;actions&quot; : [
        ///    {
        ///      &quot;parameters&quot; : [
        ///        {
        ///          &quot;name&quot; : &quot;GitBranchOrCommit&quot;,
        ///          &quot;value&quot; : &quot;${sha1}&quot;
        ///        },
        ///        {
        ///          &quot;name&quot; : &quot;GitRepoUrl&quot;,
        ///          &quot;value&quot; : &quot;https://github.com/dotnet/roslyn.git&quot;
        ///        },
        ///        {
        ///          &quot;name&quot; : &quot;GitRefSpec&quot;,
        ///          &quot;value&quot; : &quot;+refs/pull/*:refs/remotes/origin/pr/*&quot;
        ///        },
        ///        {
        ///          &quot;name&quot; : &quot;sha1&quot;,
        ///          &quot;value&quot; : &quot;origin/pr/11183/merge&quot;
        ///        },
        ///        {
        ///          &quot;name&quot; : &quot;ghpr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BuildFailure2 {
            get {
                return ResourceManager.GetString("BuildFailure2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;actions&quot;: [
        ///    {
        ///      &quot;parameters&quot;: [
        ///        {
        ///          &quot;name&quot;: &quot;GitBranchOrCommit&quot;,
        ///          &quot;value&quot;: &quot;${sha1}&quot;
        ///        },
        ///        {
        ///          &quot;name&quot;: &quot;GitRepoUrl&quot;,
        ///          &quot;value&quot;: &quot;https://github.com/dotnet/coreclr.git&quot;
        ///        },
        ///        {
        ///          &quot;name&quot;: &quot;GitRefSpec&quot;,
        ///          &quot;value&quot;: &quot;+refs/pull/*:refs/remotes/origin/pr/*&quot;
        ///        },
        ///        {
        ///          &quot;name&quot;: &quot;sha1&quot;,
        ///          &quot;value&quot;: &quot;dc3168d8d4dd2cf60cdcfad4c8a9a68174612eff&quot;
        ///        },
        ///        {
        ///          &quot;nam [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BuildFailure3 {
            get {
                return ResourceManager.GetString("BuildFailure3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;duration&quot; : 2205772,
        ///  &quot;id&quot; : &quot;4&quot;,
        ///  &quot;result&quot; : &quot;FAILURE&quot;,
        ///  &quot;timestamp&quot; : 1462491047470,
        ///  &quot;builtOn&quot; : &quot;dci-win-mbld-10&quot;
        ///}.
        /// </summary>
        internal static string Tao1BuildInfo {
            get {
                return ResourceManager.GetString("Tao1BuildInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;actions&quot; : [
        ///    {
        ///      &quot;parameters&quot; : [
        ///        {
        ///          &quot;name&quot; : &quot;GitBranchOrCommit&quot;,
        ///          &quot;value&quot; : &quot;${ghprbTargetBranch}&quot;
        ///        },
        ///        {
        ///          &quot;name&quot; : &quot;GitRepoUrl&quot;,
        ///          &quot;value&quot; : &quot;https://github.com/dotnet/roslyn-internal.git&quot;
        ///        },
        ///        {
        ///          &quot;name&quot; : &quot;GitRefSpec&quot;,
        ///          &quot;value&quot; : &quot;&quot;
        ///        },
        ///        {
        ///          &quot;name&quot; : &quot;sha1&quot;,
        ///          &quot;value&quot; : &quot;origin/pr/11091/merge&quot;
        ///        },
        ///        {
        ///          &quot;name&quot; : &quot;ghprbActualCommit&quot;, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Tao1BuildResult {
            get {
                return ResourceManager.GetString("Tao1BuildResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;actions&quot; : [
        ///    {
        ///      &quot;parameters&quot; : [
        ///        {
        ///          &quot;name&quot; : &quot;GitBranchOrCommit&quot;,
        ///          &quot;value&quot; : &quot;${ghprbTargetBranch}&quot;
        ///        },
        ///        {
        ///          &quot;name&quot; : &quot;GitRepoUrl&quot;,
        ///          &quot;value&quot; : &quot;https://github.com/dotnet/roslyn-internal.git&quot;
        ///        },
        ///        {
        ///          &quot;name&quot; : &quot;GitRefSpec&quot;,
        ///          &quot;value&quot; : &quot;&quot;
        ///        },
        ///        {
        ///          &quot;name&quot; : &quot;sha1&quot;,
        ///          &quot;value&quot; : &quot;origin/pr/11091/merge&quot;
        ///        },
        ///        {
        ///          &quot;name&quot; : &quot;ghprbActualCommit&quot;, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Tao1FailureInfo {
            get {
                return ResourceManager.GetString("Tao1FailureInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;testActions&quot; : [
        ///    
        ///  ],
        ///  &quot;duration&quot; : 1023.6126,
        ///  &quot;empty&quot; : false,
        ///  &quot;failCount&quot; : 2,
        ///  &quot;passCount&quot; : 143,
        ///  &quot;skipCount&quot; : 0,
        ///  &quot;suites&quot; : [
        ///    {
        ///      &quot;cases&quot; : [
        ///        {
        ///          &quot;testActions&quot; : [
        ///            
        ///          ],
        ///          &quot;age&quot; : 0,
        ///          &quot;className&quot; : &quot;AnalyzersNode&quot;,
        ///          &quot;duration&quot; : 102.51714,
        ///          &quot;errorDetails&quot; : null,
        ///          &quot;errorStackTrace&quot; : null,
        ///          &quot;failedSince&quot; : 0,
        ///          &quot;name&quot; : &quot;C# Analyzers Node&quot;,
        ///          &quot;skipp [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Tao1TestResult {
            get {
                return ResourceManager.GetString("Tao1TestResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this is definitely not JSON.
        /// </summary>
        internal static string TestReport1 {
            get {
                return ResourceManager.GetString("TestReport1", resourceCulture);
            }
        }
    }
}
